### PR TITLE
Try out GitHub actions

### PR DESCRIPTION
**Pull request by janschill**
GitHub actions could be used to perform some tests from our Rake test runner.

### CODE REVIEW

**Comment by janschill** [comment]
Will turn green once #51 is merged in.

**Comment by alevani** [comment]
Is it needed for the release ?

**Comment by janschill** [comment]
No, because we don't have any tests yet. I would merge this as soon as we have some tests that we can run from Rake

**Comment by alevani** [comment]
then should it be moved to draft PR maybe ?

**Comment by janschill** [comment]
>then should it be moved to draft PR maybe ?

sure

**Comment by alevani** [comment]
@janschill I just can't move it myself to draft btw

**Comment by janschill** [comment]
When https://github.com/janschill/uni-devops/pull/101 is merge, this will make sense to merge as well. Because we can then run tests checking if the code is correctly formatted.

**Comment by janschill** [comment]
I cherry picked some commit in to make the tests run. Please have a look at the GitHub Actions to see what is being tested. I think this is neat and we should definitely implement it.

**Pull request merged**
